### ISSUE TITLE
Rename to spring-security-oauth2-autoconfigure

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-security-oauth2-boot#1]
`spring-security-oauth2-boot` looks a bit odd to me. While we use the term `boot` alone in informal conversations, `boot` alone is problematic IMO in the sense that it really is `spring-boot`.

A project that contains auto-configuration is named `autoconfigure`, this is also [referenced in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming). In that  sense, I'd like also to see the module renamed to `spring-security-oauth2-autoconfigure`.

**Comment by rwinch** [comment]
Thanks for the report. I went ahead and renamed to spring-security-oauth2-autoconfigure via a separate issue since that seems clear cut to me.

What do you propose as a name for the project as an alternative? 

To me the spring-security-oauth2-spring-boot is more verbose than I'd like. Naming it as spring-security-oauth2-spring-autoconfigure is not preferred because it is to narrow (the project contains other items like docs and samples). At one point it was going to contain the cli extensions but this was removed.
