### ISSUE TITLE
The refresh token does not work after expiration of access token in zuul gateway as spring security oauth2 client

### ISSUE THREAD

**Issue by matin-reza** [spring-projects/spring-security-oauth2-boot#125]
My sample in [here](https://github.com/matin-reza/OAuth2). Every thing has been working correctly but when the access token is expired, I expect that the zuul gateway as spring-security-oauth2 client automatically get the new access token with refresh token grant type because I declare the refresh_token grant type in the gateway application.

Why is not it happen? and what configuration is lost?

After the expiration of access token the following exception is raised in zuul gateway application:

> 
Caused by: org.springframework.security.authentication.BadCredentialsException: Cannot obtain valid access token at org.springframework.cloud.security.oauth2.proxy.OAuth2TokenRelayFilter.getAccessToken(OAuth2TokenRelayFilter.java:99) ~[spring-cloud-security-2.0.0.RELEASE.jar:2.0.0.RELEASE] at org.springframework.cloud.security.oauth2.proxy.OAuth2TokenRelayFilter.run(OAuth2TokenRelayFilter.java:79) ~[spring-cloud-security-2.0.0.RELEASE.jar:2.0.0.RELEASE] at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117) ~[zuul-core-1.3.1.jar:1.3.1] at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193) ~[zuul-core-1.3.1.jar:1.3.1] ... 97 common frames omitted

**Comment by jzheaux** [comment]
@matin-reza I believe the issue is that `OAuth2TokenRelayFilter` doesn't redirect the user once the refresh token is expired. When I extend the timeout for the refresh token and adjust your gateway configuration like so:

```diff
- grant-type: authorization_code,refresh_token
+ grant-type: authorization_code
```

Then the token refreshes just fine.

I believe for `OAuth2TokenRelayFilter` to correctly handle renewing the refresh token itself, it would need to catch the `UserRedirectRequiredException` and redirect accordingly. You might consider opening a ticket at https://github.com/spring-cloud/spring-cloud-security to see if they'd be willing to add that feature.

Something like [what spring-security-oauth does with that exception](https://github.com/spring-projects/spring-security-oauth/blob/8eedb354ae0015e0f33f0c3d958d9ac84d010721/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/filter/OAuth2ClientContextFilter.java#L93) might work.

**Comment by HJK181** [comment]
@jzheaux I'm facing the same issue and wonder how token refresh could have worked for you.

I'm using `2592000` for my refresh token validity and `10` for the access token validity. My Authorization servers issues JWT tokens and I'm also using Zuul as a `@ZuulProxy` with `@EnableOAuth2Sso` and `@EnableResourceServer`. 

I'm also providing a `OAuth2RestTemplate` bean but every time my access token expires, I'm facing a `UserRedirectRequiredException` in the `OAuth2TokenRelayFilter` when a new access token get's acquired by the `restTemplate`. This somehow makes sense for me as I use `authorization_code` as grant type (which the example also does).

After the above mentioned exception is thrown the `AccessTokenContextRelay#copyToken` method stores and access token with null values for `expiration`, `refreshToken` and `scope` in the `DefaultOAuth2ClientContext` . Thus subsequent calls to `OAuth2TokenRelayFilte#getAccessToken` will always return that expired token as a refresh to the token will only be done if it'S not expired `OAuth2RestTemplate#getAccessToken`.

Consequently all subsequent requests will return an `InvalidTokenException` with an error description of `Access token expired`.

I know that Zuul is in maintenance mode but I would rely appreciate some help how to solve this issue.

The main issue I'm trying to solve is that I'm facing `HttpRetryException: cannot retry due to server authentication, in streaming mode` exceptions when calling some downstream services from time to time. I'm pretty sure those are `401` errors which can't be handles by the default HTTP client. But I can't reproduce those. It looks like after I restart my services, calls to downstream services just work fine until the next working day. Than after expiry of the Zuul session or JWT - I'm using a `JdbcTokenStore` to store the JWT (this might be silly) - the downstream calls just fail.

I now try to reproduce this with changes to the token validity which fails for the above mentioned reasons :/
