### ISSUE TITLE
Update spring-security-oauth2 to 2.3.7.RELEASE

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-security-oauth2-boot#147]
The last release (2.1.6) missed the fix for [CVE-2019-11269](https://pivotal.io/security/cve-2019-11269).

**Comment by jzheaux** [comment]
@OrangeDog thanks for the report. This project needs to have [this ticket](https://github.com/spring-projects/spring-security-oauth/issues/1616) fixed in order to upgrade to a newer `spring-security-oauth` dependency.

If you are not using the check token endpoint, then you should be fine to follow the steps indicated in that CVE to override the spring-security-oauth dependency.

**Comment by jzheaux** [comment]
I've updated the ticket description to indicate the next viable version that this project could be updated to.

**Comment by OrangeDog** [comment]
> the steps indicated in that CVE

They assume Boot 1.x, not Boot 2.x.
That just means you need to add it to `<dependencyManagement>` though.

**Comment by OrangeDog** [comment]
Hold the press if possible!
Turns out 2.3.7.RELEASE broke a lot of de-serialisation due to attempting to add a closed whitelist.
That's been reverted for 2.7.8.RELEASE, but not released yet.
