### ISSUE TITLE
OAuth2AccessToken Class Serialize And Deserialize Problem

### ISSUE THREAD

**Issue by wangzhangmao** [spring-projects/spring-security-oauth2-boot#177]
When my project is using FastJson as a serialization tool, other projects using JaskJson will not get the AccessToken correctly through ClientCredentials.

![企业微信截图_15716508174792](https://user-images.githubusercontent.com/18365870/67194576-f56e6500-f429-11e9-914f-6fbc979e5f76.png)

**Comment by jzheaux** [comment]
@wangzhangmao thanks for reaching out. Would you please log this issue to [the Spring Security OAuth project](https://github.com/spring-projects/spring-security-oauth/issues) since that is where that code is maintained? 

Please link that ticket here so that folks in the future can follow the conversation. Also, when you are reporting there, you will likely reach a resolution faster if you describe there exactly what problem you are seeing and a reproducer that demonstrates the flaw.
