### ISSUE TITLE
Security Issue with Refresh Token

### ISSUE THREAD

**Issue by agokulravikumar** [spring-projects/spring-security-oauth2-boot#186]
There is an issue with the refresh token using JDBCTokenStore (Not sure if it exists in other store types)

**spring-security-oauth2  2.3.5 RELEASE**

When I have the **grant_type** as **refresh_token**, for the first request everything works fine. But from the next refresh token request it throws invalid refresh token error.

In my analysis found that, during refresh_token request, the data in **oauth_refresh_token** table is not getting replaced. So it creates a mismatch between **oauth_access_token.refresh_token** and **oauth_refresh_token.token_id**

Also, when I try refresh_token request with the first created refresh token it is still responding with new access token each time which is a **serious security threat**

Due to this multiple access token are generated in **oauth_access_token** table for the same username and sometimes it throws Exception due to multiple records.

Can someone update me on this ?

**Comment by jzheaux** [comment]
@agokulravikumar thank you for raising your concerns.

Will you please do one of two things so we can address them efficiently:

1. If you believe this to be a genuine security issue, please report it to https://pivotal.io/security instead of posting a GitHub ticket
2. If you believe that it is simply a bug, please file it with https://github.com/spring-projects/spring-security-oauth instead. It can be a bit confusing, but this project (`spring-security-oauth2-boot`) is for Boot autoconfiguration of `spring-security-oauth`.

I'll close this ticket, but please feel free to reach out if you have any other questions that aren't answered on https://pivotal.io/security.
