### ISSUE TITLE
Why is custom exception handling so complicated and not able to handle all the exceptions at the same time？？？

### ISSUE THREAD

**Issue by pog2g** [spring-projects/spring-security-oauth2-boot#199]
1.Why is exception handling so complicated??
2.Why can't authorization code mode token management share oauth2 TokenStore????
3.WebResponseExceptionTranslator, AuthenticationEntryPoint intercept all exceptions？？？

**Comment by jzheaux** [comment]
Sorry to see you so frustrated, @pog2g. 

Now, we won't get very far with these questions in a forum like this, so I'm going to close this ticket. However, please feel free to log new tickets if you have a concrete proposal or believe you've found a bug.

Otherwise, I recommend you engage the community on [Gitter](https://gitter.im/spring-projects/spring-security) or [Stack Overflow](https://stackoverflow.com/) and linking here to your findings.
