### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-oauth2-boot#2]
From: #1

spring-security-oauth2-boot looks a bit odd to me. While we use the term boot alone in informal conversations, boot alone is problematic IMO in the sense that it really is spring-boot.

**Comment by rwinch** [comment]
@snicoll

What do you propose as a name for the project as an alternative? 

To me the spring-security-oauth2-spring-boot is more verbose than I'd like. Naming it as spring-security-oauth2-spring-autoconfigure is not preferred because it is to narrow (the project contains other items like docs and samples). At one point it was going to contain the cli extensions but this was removed.

**Comment by snicoll** [comment]
Why does it need to be a separate project? Surely I understand that you can't have a cycle for the version we use for Spring  Boot `1.x` but you could create a branch  for that and have `master` containing the content of this project as well. It doesn't matter since we'll never have a dependency in Spring Boot 2 anymore. 

Given that `spring-security-oauth` is now legacy and superseded by Spring Security 5, this feels quite natural to me (in comparison to create a brand new repository).

**Comment by vpavic** [comment]
Personally I also prefer this to be a part of [spring-projects/spring-security-oauth](https://github.com/spring-projects/spring-security-oauth) as it seems the most natural approach.

With separate repo there's a whole set of things to manage around the new project (think build/release/infra/etc) which I think is quite an overhead for something that, like @snicoll points out, is being superseded.

In most cases projects that provide their own Spring Boot auto-configuration support follow the same repo approach. This has an obvious advantage that users can rely on release version when matching modules, i.e. `spring-security-oauth2` and `spring-security-oauth2-autoconfigure`.

OTOH with the separate repo, and therefore separate release cycle, it isn't obvious to users which versions to use together. So if someone wants to use the old Spring Security OAuth2 with JWTs in a Spring Boot project they would need to declare 3 dependencies (`spring-security-oauth2`, `spring-security-jwt` and `spring-security-oauth2-autoconfigure`) and all would have different version numbers which isn't quite user friendly IMO. Of course, that could be easily handled by introducing the starter module, but then again we have a situation where users needs to declare `spring-security-oauth2-starter` of version X to use `spring-security-oauth2` of version Y.

**Comment by rwinch** [comment]
We do want this to be separate repository because we want separate release cycle for the project. I do not want to maintain multiple branches for the other code which will not differ between Spring Framework 4.x and 5.x generations.

> With separate repo there's a whole set of things to manage around the new project (think build/release/infra/etc) which I think is quite an overhead for something that, like @snicoll points out, is being superseded.

Additionally, I prefer using the security teams new Gradle plugins for managing as many things as possible as it provides consistency across our projects. The legacy OAuth project is already established its infrastructure and will likely continue to use this old setup. However, I don't want this to impact the any new code. The new setup allows creating branches, releasing, etc with ease.

Finally, the old OAuth repository is already managing multiple projects in a single repository and it makes releases a bit strange since we tag releases for JWT with `jwt<version>`. It is strange that the OAuth code is tagged with JWT versioning system. I do not want to continue this confusion for the Boot 2 integration.

**Comment by snicoll** [comment]
> We do want this to be separate repository because we want separate release cycle for the project

Why?

Arguably, you're not going to release anything for the `1.5.x` version now so effectively this is not a problem.

**Comment by jgrandja** [comment]
The other thing to point out is the autoconfig depends on `org.springframework.social`. We don't want the `spring-security-oauth` repo to depend on `org.springframework.social`

**Comment by rwinch** [comment]
> Arguably, you're not going to release anything for the 1.5.x version now so effectively this is not a problem.

There will still be patch releases for quite some time to come.

**Comment by rwinch** [comment]
I'd also like to point out moving this project to Spring Security OAuth doesn't really solve our problem since it will likely still be a nested folder within the repo needing a name. The old project doesn't even have conventional docs (it lives in github and is fairly sparse), so putting only the Boot 2 + OAuth docs in the main project will likely cause quite a bit of confusion.

**Comment by snicoll** [comment]
> The other thing to point out is the autoconfig depends on org.springframework.social

😓

**Comment by snicoll** [comment]
Alright my vote goes to `spring-security-oauth2-auto-configuration`

**Comment by vpavic** [comment]
> The other thing to point out is the autoconfig depends on `org.springframework.social`.

I don't think that the parts of auto-configuration code that depend on Spring Social should get migrated to the new `spring-security-oauth2-autoconfigure` module regardless of the repo that hosts the code.

It was a different situation when that code was a part of Spring Boot, since Boot also provided both dependency management and auto-configuration for Spring Social as well (note that it does not any more in 2.0).

IMO `spring-security-oauth2-autoconfigure` should only take into consideration integrating `spring-security-oauth2` and Spring Boot, adding anything else to the mix complicates matters and is a maintenance risk going forward (due to alignment of dependency versions).

**Comment by rwinch** [comment]
> note that it does not any more in 2.0

Right but Spring Social provides that configuration now. So it still exists, but it has been moved (just as it was for OAuth). 

We cannot just drop the Spring Social pieces. Otherwise, we run into the same question we have for Spring Security OAuth2...how do I use it with Spring Boot 2. Overall, this needs to be very passive for users that have existing functionality as that is the goal.

**Comment by snicoll** [comment]
For the record, I agree with Vedran on the principle. I haven't looked enough to figure out what feature would actually be lost but considering that Spring Social support has been completely removed from Spring Boot 2, it doesn't strike me as crazy to consider removing those bits here as well.

**Comment by rwinch** [comment]
The support has been extracted just like OAuth. This puts Social in a very
similar situation as OAuth. If we remove the Social + OAuth support we are
hurting the user transition rather than helping it (the point of this
project). My goal for this project is to provide as similar OAuth
experience to Boot 1 in Boot 2 to ease transition time and give the new
OAuth support time to catch up.

**Comment by snicoll** [comment]
Can we please move along with this? Having a module name with `boot` in it makes me cringe.

**Comment by rafaelrenanpacheco** [comment]
Hi there!

Was `spring-security-starter-oauth2` considered? The main dependency is `spring-security-oauth2`, so `spring-security-starter-oauth2` makes more sense for a Spring Boot project.

**Comment by lexburner** [comment]
so many project names are associated with oauth2 like 'spring-security-oauth2','spring-security-oauth2-autoconfigure','spring-cloud-starter-oauth2' and more...
as a developer,these confuse me.
a statement describes the difference btween them may help a lot.

**Comment by jzheaux** [comment]
@lexburner I sympathize. Part of your heartburn is due to the fact that Spring Security's OAuth2 support is [being brought into native Spring Security](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) in favor of continuing to release as a plugin. In the meantime, there are basically two sets of dependencies to negotiate. It's something that we are working to simplify. We've published a [Feature Matix](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix) that you can use to navigate based on what features you need. The second column in that matrix describes when this project comes into play.

@rafaelrenanpacheco `spring-security-starter-oauth2` or `spring-boot-starter-security-oauth2` might be okay, but the semantics are a little bit off. Starter projects tend to simply be a collection of dependencies, one of them being `spring-boot-autoconfigure`, for example. In this case, the project doesn't publish a starter artifact and it has an `autoconfigure` project of its own, making it not look like other "starter" projects.

Regarding the name, then, `spring-boot` itself has `spring-boot-autoconfigure` as well as other projects for the benefit of configuring Spring.

What makes sense to me then, is to formulate the analogous logic for this project:

`spring-security-oauth2-boot` itself has `spring-security-oauth2-autoconfigure` as well as other projects for the benefit of configuring Spring Security OAuth2.

This project follows the release train for `spring-boot`, and, in that sense, is a parallel project to it (albeit narrowly focused).

The analogy isn't perfect, but I think it's the closest we have.
