### ISSUE TITLE
OAuth2SsoDefaultConfiguration should ignore or unprotect /error

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-security-oauth2-boot#22]
Otherwise you get a redirect loop for an unauthenticated user, e.g. if the auth server is down or unable to issue a token. This wasn't an issue in Spring Boot 1.5 because /error was always ignored, but it isn't the case in 2.0.

**Comment by jzheaux** [comment]
@dsyer, I had a quick chat with @rwinch about this, and while I do think it would be convenient for the user, it is better to stick to the Spring Boot defaults. This way, we can maintain a secure-by-default stance. When Spring Boot 2.x stopped ignoring "/error", it was a good security move because it requires the user to explicitly choose to open it up.

I saw how you changed your samples in the related bug, and I think this is the approach that we want to transmit to users, and that is to explicitly permit "/error".

What I'd prefer then is to add documentation that informs users of the need to map "/error" themselves, should they want it to be public. The documentation would also highlight this infinite redirect as one motivation for doing so.
