### ISSUE TITLE
AuthenticationSuccessEvent fires twice times when post to /oauth/token success

### ISSUE THREAD

**Issue by isscy** [spring-projects/spring-security-oauth2-boot#272]
I watch AuthenticationSuccessEvent but have twice event fries ,  i know they from  **client authentication** and **user authentication**  , but event.getSource() result all is instance of UsernamePasswordAuthenticationToken.

so i want to know why In the **BasicAuthenticationFilter** (or **ClientCredentialsTokenEndpointFilter**) , convert request to UsernamePasswordAuthenticationToken,  cause i can not judgment event trigger source

**Comment by jzheaux** [comment]
Thanks for reaching out, @isscy.

`BasicAuthenticationFilter` adds an `AuthenticationDetailsSource` to the `Authentication`, and you can inspect it with `Authentication#getDetails`.

You can also customize this with additional information by creating your own instance of `AuthenticationDetailsSource` like so:

```java
http
    .httpBasic((basic) -> basic
        .authenticationDetailsSource(...)
    );
```

Or, it's not uncommon to need to customize the principal to include domain-specific information about the user. You might be able to tell by calling `Authentication#getPrincipal` and inspecting the differences there.

In the future, we prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). For usage questions, [Stack Overflow](https://stackoverflow.com/) is preferred. That said, I hope my answer was helpful. If you need more help, please post a question to Stack Overflow and link that question back to this ticket so that others can find it.
