### ISSUE TITLE
Consider registering an `AuthenticationManager` bean if not present 

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security-oauth2-boot#30]
Related to [this](https://github.com/spring-projects/spring-boot/issues/11136#issuecomment-381338605). The out of the box experience for password grant is tedious because the user needs to provide a `WebSecurityConfigurerAdapter` just to expose an `AuthenticationManager` bean. Maybe there's a way to reduce this overhead.

**Comment by PhazedOut** [comment]
You can add the bean like [this](https://github.com/spring-projects/spring-security-oauth2-boot/issues/29).

**Comment by jzheaux** [comment]
The out-of-the-box setup actually doesn't require a user-defined `AuthenticationManager` as is described in the documentation--it's just a handful of properties and annotating a configuration class with `@EnableAuthorizationServer`.

However, the use case @mbhave has pointed out is that, once a user needs to extend `AuthorizationServerConfigurer`, then auto-configuration backs off, meaning that the code no longer has an opportunity to introduce an `AuthenticationManager` with default configuration (a default user and random password).

As @PhazedOut pointed out, there is a way to obtain a default-configured `AuthenticationManager` via `AuthenticationConfiguration`:

```java
public class ServerConfig extends AuthorizationServerConfigurer {
    private AuthenticationManager authenticationManager;

    public ServerConfig(AuthenticationConfiguration authenticationConfiguration) {
        this.authenticationManager = authenticationConfiguration.getAuthenticationManager();
    }

    @Override
    public void configure(AuthorizationServerEndpointsConfigurer endpoints)
        throws Exception {
        endpoints.authenticationManager(this.authenticationManager);
    }
}
```

Beyond that, yes, the user base is configured in `WebSecurityConfigurerAdapter`, but, if it is just a matter of configuring the identification of a user, given credentials, then the user can simply expose a `UserDetailsService`:

```java
public class UserConfig extends WebSecurityConfigurerAdapter {
    @Override
    @Bean
    public UserDetailsService userDetailsService() {
        return (username) -> {
            // user-custom way to locate end user
        }
    }
}
```

So, those are some ways to avoid creating your own `AuthenticationManager`.

Still, I haven't quite addressed the question, which is whether or not we can be smart about it and notice that there is no `AuthenticationManager` when `AuthorizationServerEndpointsConfiguration` is exposing its beans, and I think that the answer it is certainly worth looking at, though since that enhancement would be in `spring-security-oauth2`, which is in maintenance mode, we might decide to simply point people to the new offering.

To that end, though, I've logged an issue in `spring-security-oauth2` for further discussion: https://github.com/spring-projects/spring-security-oauth/issues/1465
