### ISSUE TITLE
AuthenticationSuccessEvent not published when /oauth/token

### ISSUE THREAD

**Issue by Alice52** [spring-projects/spring-security-oauth2-boot#354]
Hi, I'm in troubling for AuthenticationSuccessEvent publishing.

1. when i post /oauth/token in TokenEndpoint, it just publishes AuthenticationSuccessEvent for client authentication, 
2. and it donot publish AuthenticationSuccessEvent for user authentication, is it expectation behavior of framework? Why?
3. And if it publish AuthenticationSuccessEvent   for user authentication, may i know the source code of  this logic? Thanks.
@jzheaux  @rwinch

**Comment by jzheaux** [comment]
Hi, @Alice52. Thanks for getting in touch! It feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to [use GitHub issues only for bugs and enhancements](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add more detail if you feel this is a genuine bug.

**Comment by jzheaux** [comment]
Also, if you are able, please consider trying out [Spring Authorization Server](https://github.com/spring-projects/spring-authorization-server), which replaces this project.
