### ISSUE TITLE
Release 2.0.0.RC2

### ISSUE THREAD

**Issue by tanadeau** [spring-projects/spring-security-oauth2-boot#4]
Thanks for creating this project. It's helped a great deal in our upgrade to Spring Boot 2.0 (RC1 for now).

Can you create a milestone build that works with RC1 or one for RC2 when that's released soon? My project can't use SNAPSHOT builds other than for investigation tasks due to build reproducibility.

Thanks, again!

**Comment by rwinch** [comment]
@tanadeau We plan to do a release that works with RC2 as soon as it is released

**Comment by tanadeau** [comment]
RC2 was released this morning 😄

**Comment by tanadeau** [comment]
@rwinch Any update on this? Thanks for any info.

**Comment by rwinch** [comment]
I'm currently waiting on a release from Spring Social

**Comment by spencergibb** [comment]
This is now a block on spring-cloud-security since it depends on this project.

From @habuma

> I'm so confused as to why that depends on Spring Social. And until just moment ago was unaware that I even needed to do another release.
I can certainly cut a milestone release that builds against RC2...that's not a problem. But I start getting concerned about GA stuff, because the going plan was that Spring Social isn't going to be cutting any more GA releases, unless it's maintenance on the current set of GAs.

Looks like there is some confusion here. Either social needs to be dropped for boot 2 or it needs to be officially supported.

**Comment by rwinch** [comment]
@spencergibb After speaking with @habuma today it appears we will release using the 1.5.x version of Spring Social. From what he said this aligns with Spring Integration's plans too. At this point with Spring Boot GA around the corner we will just release with Spring Boot 2.0.0.RELEASE on Wednesday.

**Comment by rwinch** [comment]
Apparently there is significant value in having an RC2 to the Spring Cloud team, so we plan on releasing RC2 shortly

**Comment by tanadeau** [comment]
RC2 is not in the Spring milestone Maven repo.

**Comment by rwinch** [comment]
Thanks @tanadeau! Yes it can be found at http://repo.spring.io/milestone/org/springframework/security/oauth/boot/spring-security-oauth2-autoconfigure/2.0.0.RC2/

**Comment by spencergibb** [comment]
Thanks, @rwinch for the effort. I know it will be duplicated again shortly, but it helped us out.

**Comment by rwinch** [comment]
@spencergibb No worries. Glad I could help out!
