### ISSUE TITLE
OAuth2RestOperationsConfiguration$DefaultOAuth2ClientContext and  OAuth2AuthorizedClient conflict

### ISSUE THREAD

**Issue by YaCoHuang** [spring-projects/spring-security-oauth2-boot#51]
duplicate bean

**Comment by jzheaux** [comment]
@huangyangcong could you please share your configuration? It looks like you may be using `spring-security-oauth2` as well as `spring-security-oauth2-client`.

**Comment by jzheaux** [comment]
@huangyangcong, this was addressed in https://github.com/spring-projects/spring-security-oauth2-boot/issues/39 which it appears that `spring-cloud-starter-oauth2` may not pick up until their 2.1.0.RC1 release.

In the meantime, please use the following property in your application.yml:

```
spring.main.allow-bean-definition-overriding: true
```

Let me know if that works for you.

The demo app you uploaded also revealed a related issue, which is why I'm not just yet recommending that you simply override the `spring-security-oauth2-autoconfigure` dependency in your pom just yet.

**Comment by jzheaux** [comment]
@huangyangcong also, OOC, I noticed that you are using @EnableOAuth2Client also with client credentials, which isn't necessary. From the [`@EnableOAuth2Client` java doc](https://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/config/annotation/web/configuration/EnableOAuth2Client.html):

> Enable configuration for an OAuth2 client in a web application that uses Spring Security and wants to use the Authorization Code Grant from one or more OAuth2 Authorization servers.

Is there a reason that you are using `@EnableOAuth2Client` and client credentials together? (Wondering if there is something in the docs that is suggesting this)?

**Comment by huangyangcong** [comment]
I Just learning springcloud and oauth2
http://projects.spring.io/spring-security-oauth/docs/oauth2.html
`Different grant types have different concrete implementations of OAuth2ProtectedResourceDetails (e.g. ClientCredentialsResource for "client_credentials" grant type). For grant types that require user authorization there is a further property:`
I want to change the authorization code to client credentials。

谢谢您的提醒
Thank you for reminding me
