### ISSUE TITLE
After opening @EnableOAuth2Sso, request authorization. Infinite redirection/login upon successful authorization

### ISSUE THREAD

**Issue by niyaode** [spring-projects/spring-security-oauth2-boot#83]
![tim 20190203110036](https://user-images.githubusercontent.com/27875141/52172066-f6c80680-27a2-11e9-80c7-69beef3f4d33.png)

### Authorization server configuration
![tim 20190203104523](https://user-images.githubusercontent.com/27875141/52171980-8e2c5a00-27a1-11e9-9b0d-fedc63edb16d.png)

![tim 20190203104657](https://user-images.githubusercontent.com/27875141/52171984-984e5880-27a1-11e9-96cf-c7fa06c100ac.png)

![tim 20190203104808](https://user-images.githubusercontent.com/27875141/52171986-9e443980-27a1-11e9-8631-2123851f3a0c.png)

![tim 20190203105940](https://user-images.githubusercontent.com/27875141/52172064-d9933800-27a2-11e9-9695-f89a255378b4.png)

### Client server
![tim 20190203105450](https://user-images.githubusercontent.com/27875141/52172036-70132980-27a2-11e9-90f2-0431a76438b0.png)
![tim 20190203105546](https://user-images.githubusercontent.com/27875141/52172039-73a6b080-27a2-11e9-97d2-f65feb0225f4.png)

For these configurations

**Comment by niyaode** [comment]
It has been solved because there is no spring-security-jwt. But I don't understand why this configuration can still succeed without   security.oauth2. resource.jwt.key-uri  authorization in spring-boot-sample-web-secure-github projects.



![tim 20190203113736](https://user-images.githubusercontent.com/27875141/52172327-2d545000-27a8-11e9-86e3-d9203dc93865.png)

This is the configuration of the spring-boot-sample-web-secure-github project.

![tim 20190203115059](https://user-images.githubusercontent.com/27875141/52172438-05fe8280-27aa-11e9-87b5-17789ad0a2d1.png)

**Comment by jzheaux** [comment]
The infinite redirect is typically caused by the client not being able to verify the token due some kind of misconfiguration. One thing I'd point out is that the antmatchers on your client are configured in the reverse. Basically, you are doing:

```java
authorizeRequests()
    .anyRequest().authenticated()
    .antMatchers("/error", "/admins/**", "/login").permitAll()
```

Which is the equivalent of doing:

```java
if ( isAuthenticated() ) {
    // ... do it
} else {
    return 403;
}

if ( path == "/error" | "/admins/**" | "/login" ) {
    // ... do it
}
```

Because `anyRequest` matches everything, your other endpoints are never tested. I'd recommend doing:

```java
authorizeRequests()
    .antMatchers("/error", "/admins/**", "/login").permitAll()
    .anyRequest().authenticated()
```
instead.

If that doesn't fix your issue, will you please do two things for me? First, please create a simple, self-contained project that reproduces the issue. Second, please post that to a StackOverflow question. Then, it will be a lot simpler to import and test and give you some advice.

Also, for further support questions, please post to StackOverflow. As an alternative, you can hit up the Gitter chat room.
