### ISSUE TITLE
In the @enableoauth2sso client, there is a problem in getting user information

### ISSUE THREAD

**Issue by niyaode** [spring-projects/spring-security-oauth2-boot#91]
I want to get the principal object, which is now a string.How do I add principal information in JWT
This is my example project [GitHub](https://github.com/niyaode/OAuthSSO)
I have read [OAuth2 Developers Guide](https://projects.spring.io/spring-security-oauth/docs/oauth2.html#authorization-server-configuration) and [OAuth2 Boot](https://docs.spring.io/spring-security-oauth2-boot/docs/current-SNAPSHOT/reference/htmlsingle/) but still can't find the answer

![tim 20190221164202](https://user-images.githubusercontent.com/27875141/53155623-6722b480-35f8-11e9-9c91-a235cf517ce7.png)
![tim 20190221164321](https://user-images.githubusercontent.com/27875141/53155624-67bb4b00-35f8-11e9-8343-5936aa3a20bb.png)

**Comment by jzheaux** [comment]
@niyaode GitHub isn't the preferred place for support requests.

Preferably, you'd [post a question to StackOverflow](https://stackoverflow.com/questions/ask) so that it increases the visibility of your question (you get the entire community to help you). I'm on there regularly, too.

I'm going to close these questions, not because I don't want to help (indeed I do), but because I want the community to be able to gain from the exchange as well.

You can also hop on https://gitter.im/spring-projects/spring-security-oauth and usually find several community members as well as a Spring Security team member hanging out there.
