### ISSUE TITLE
SSO login, how do I specify the path to redirect after successful authentication under the client/login path

### ISSUE THREAD

**Issue by niyaode** [spring-projects/spring-security-oauth2-boot#92]
When the client is not logged in, it redirects the authorization service to log in.Login successful return client /login path authentication successful.It will jump to/root path after successful authentication. How do I specify the path to jump to after successful authentication

**Comment by jzheaux** [comment]
@niyaode GitHub isn't the preferred place for support requests.

Preferably, you'd [post a question to StackOverflow](https://stackoverflow.com/questions/ask) so that it increases the visibility of your question (you get the entire community to help you). I'm on there regularly, too.

I'm going to close these questions, not because I don't want to help (indeed I do), but because I want the community to be able to gain from the exchange as well.

You can also hop on https://gitter.im/spring-projects/spring-security-oauth and usually find several community members as well as a Spring Security team member hanging out there.
