### ISSUE TITLE
Customize the authorization server login page, and 401 appears after logging in through AJAX

### ISSUE THREAD

**Issue by niyaode** [spring-projects/spring-security-oauth2-boot#93]
I configured the custom login page on the authorization server and logged in through AJAX.When the authorization is successfully returned to the client, 401 appears
![tim 20190222155011](https://user-images.githubusercontent.com/27875141/53228221-7cace280-36bb-11e9-9f6a-0e4a33884f7d.png)
![tim 20190222155544](https://user-images.githubusercontent.com/27875141/53228225-7dde0f80-36bb-11e9-808a-85aea5dc759c.png)

**Comment by jzheaux** [comment]
@niyaode GitHub isn't the preferred place for support requests.

Preferably, you'd [post a question to StackOverflow](https://stackoverflow.com/questions/ask) so that it increases the visibility of your question (you get the entire community to help you). I'm on there regularly, too.

I'm going to close these questions, not because I don't want to help (indeed I do), but because I want the community to be able to gain from the exchange as well.

You can also hop on https://gitter.im/spring-projects/spring-security-oauth and usually find several community members as well as a Spring Security team member hanging out there.
