### ISSUE TITLE
Include spring-security-oauth2-autoconfigure in io.spring.dependency-management 

### ISSUE THREAD

**Issue by kaidowei** [spring-projects/spring-security-oauth2-boot#94]
Hello,
we use the `io.spring.dependency-management` (Version `2.1.3.RELEASE`) gradle plugin to manage our dependency. This works very good, but the 
            `org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.1.3.RELEASE` artifact is not included there.

Can you please add this artifact to the bom?

Thank you.

**Comment by jzheaux** [comment]
Hi, @kaidowei, thanks for the suggestion. 

Actually, this project is downstream from that release, which is why it isn't included.

**Comment by lanwen** [comment]
Hello @jzheaux, 

can you describe more precisely what "downstream from that release" means?

**Comment by jzheaux** [comment]
@lanwen, what I mean is that when Spring Boot releases - and by association, the dependency bom for that same version - this project has not yet released. In order for this project to be included in the Boot release, its release would need to be managed by the Boot team.

While there are several similarities between this project and the other projects that the Boot team manages, this specific project is actually managed by the Security team while Boot transitions from the [related plugin project](https://spring.io/projects/spring-security-oauth) to [built-in OAuth 2.0 support](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security).

The team's committed, though, to follow the Boot release cycle so that users can easily use the same property in your gradle configuration to specify the boot version as well as the oauth2-boot version.
